<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>21187</id>
    <title>Flaky test: TestRunStdinBlockedAfterContainerExit</title>
    <description>
        <paragraph id="1">
            <sentence id="1.1">Seen failing on WindowsTP4 in https://github.com/docker/docker/pull/21183 (https://jenkins.dockerproject.org/job/Docker-PRs-WoW-TP4/2677/console)</sentence>
        </paragraph>
    </description>
</bug>
