<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>14660</id>
    <title>Docker Search not working for private repos</title>
    <description>
        <paragraph id="1">
            <sentence id="1.1">Description of problem:
This causes docker-compose errors, but I believe that this is a docker issue.</sentence>
            <sentence id="1.2">When doing a 'docker search &lt;organization-name&gt;' (after an appropriate 'docker login'), only public repos are shown.</sentence>
            <sentence id="1.3">This also means that 'docker-compose up's will fail (not sure if relevant).</sentence>
            <sentence id="1.4">However, manually docker pulling with organization-name/repo-name works.</sentence>
        </paragraph>
        <paragraph id="2">
            <sentence id="2.1">'docker version':</sentence>
        </paragraph>
        <paragraph id="3">
            <sentence id="3.1">"'
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
"'</sentence>
        </paragraph>
        <paragraph id="4">
            <sentence id="4.1">'docker info':</sentence>
        </paragraph>
        <paragraph id="5">
            <sentence id="5.1">"'
Containers: 3
Images: 97
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 103
 Dirperm1 Supported: false
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 3.86 GiB
Name: docker-vagrant
ID: &lt;not sure if should be displayed&gt;
Username: alexmwu
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
"'</sentence>
        </paragraph>
        <paragraph id="6">
            <sentence id="6.1">'uname -a':
'Linux docker-vagrant 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux'</sentence>
        </paragraph>
        <paragraph id="7">
            <sentence id="7.1">Environment details (AWS, VirtualBox, physical, etc.):
Virtualbox through Vagrant</sentence>
        </paragraph>
        <paragraph id="8">
            <sentence id="8.1">How reproducible:
fails every time</sentence>
        </paragraph>
        <paragraph id="9">
            <sentence id="9.1">Steps to Reproduce:</sentence>
            <sentence id="9.2">1 'docker login'</sentence>
            <sentence id="9.3">2 'docker search &lt;organization-name&gt;' - This will fail to find private repos</sentence>
            <sentence id="9.4">3 'docker-compose up' will fail since it cannot find private repos.</sentence>
            <sentence id="9.5">4 'docker pull &lt;organization-name/&lt;private-repo-name&gt;' (works)</sentence>
        </paragraph>
        <paragraph id="10">
            <sentence id="10.1">Actual Results:</sentence>
        </paragraph>
        <paragraph id="11">
            <sentence id="11.1">"'</sentence>
            <sentence id="11.2">$ docker-compose up</sentence>
            <sentence id="11.3">Creating repo_name_1...</sentence>
            <sentence id="11.4">Pulling image org-name/repo-name:latest...</sentence>
            <sentence id="11.5">Pulling repository org-name/repo-name</sentence>
            <sentence id="11.6">Traceback (most recent call last):</sentence>
            <sentence id="11.7"> File "&lt;string&gt;", line 3, in &lt;module&gt;</sentence>
            <sentence id="11.8"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 31, in main</sentence>
            <sentence id="11.9"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch</sentence>
            <sentence id="11.10"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 27, in dispatch</sentence>
            <sentence id="11.11"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch</sentence>
            <sentence id="11.12"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 59, in perform_command</sentence>
            <sentence id="11.13"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 464, in up</sentence>
            <sentence id="11.14"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 208, in up</sentence>
            <sentence id="11.15"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in recreate_containers</sentence>
            <sentence id="11.16"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 199, in create_container</sentence>
            <sentence id="11.17"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 37, in stream_output</sentence>
            <sentence id="11.18"> File "/code/build/docker-compose/out00-PYZ.pyz/compose.progress_stream", line 50, in print_output_event</sentence>
            <sentence id="11.19">compose.progress_stream.StreamOutputError: Error: image org-name/repo-name:latest not found</sentence>
            <sentence id="11.20">"'</sentence>
        </paragraph>
        <paragraph id="12">
            <sentence id="12.1">Expected Results:
A 'docker search' and 'docker-compose' success (lists private repos and starts containers, respectively)</sentence>
        </paragraph>
        <paragraph id="13">
            <sentence id="13.1">Additional info:
I am not sure if this is a bug or a new feature.</sentence>
            <sentence id="13.2">Either way, any help would be appreciated.</sentence>
        </paragraph>
    </description>
</bug>
