<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
    <id>HHH-4522</id>
    <title>CallbackAndDirtyTest throws exception when run against PostgreSQL</title>
    <description>
        <paragraph id="1">
            <sentence id="1.1">The exception is:</sentence>
        </paragraph>
        <paragraph id="2">
            <sentence id="2.1">PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00</sentence>
        </paragraph>
        <paragraph id="3">
            <sentence id="3.1">The problems is that the Person entity defines a character property which is in one case not set in this test.</sentence>
            <sentence id="3.2">The default character value, however, causes this exception against PostgreSQL (ant potentially other databases)</sentence>
        </paragraph>
    </description>
</bug>
