<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bug>
	<id>14536</id>
	<title>Docker build from private image not authorized?</title>
	<description>
		<paragraph id="1">
			<sentence id="1.1">We recently upgraded to docker 1.7 from docker 1.5 (yesterday).</sentence>
			<sentence id="1.2">Now we're experiencing an odd issue, our docker builds can't pull our private images via dockerfile.</sentence>
			<sentence id="1.3">CLI docker pulls work just fine though... Here's how to reproduce:
Note: bunchballdev is our company dockerhub group
#login
$ sudo docker login
Username: [username]
Password:
Email: stuff@example.com
WARNING: login credentials saved in /home/[homedir]/.</sentence>
			<sentence id="1.4">docker/config.</sentence>
			<sentence id="1.5">json
Login Succeeded</sentence>
		</paragraph>
		<paragraph id="2">
			<sentence id="2.1">##the most basic dockerfile
$ cat Dockerfile
FROM bunchballdev/fedora
RUN echo "got here"</sentence>
		</paragraph>
		<paragraph id="3">
			<sentence id="3.1">##building it responds with the error message that it doesn't exist, but also could be that I'm not authorized
$ sudo docker build .</sentence>
			<sentence id="3.2">Sending build context to Docker daemon 20.48 kB
Sending build context to Docker daemon
Step 0 : FROM bunchballdev/fedora
Pulling repository bunchballdev/fedora
Error: image bunchballdev/fedora:latest not found</sentence>
		</paragraph>
		<paragraph id="4">
			<sentence id="4.1">##clearly it not only exists, but I'm authorized to pull it
$ sudo docker pull bunchballdev/fedora
latest: Pulling from bunchballdev/fedora
48ecf305d2cf: Pull complete
ded7cd95e059: Pull complete
08146ed4d2fb: Pull complete
d6683cfa8605: Pull complete
f7490fdf7bd6: Pull complete
33a9229518a7: Already exists
Digest: sha256:45df6c06cab4211fbfd730e608e7ef374c2fec8fb9ccd6b849ca46f3128965dc
Status: Downloaded newer image for bunchballdev/fedora:latest</sentence>
		</paragraph>
		<paragraph id="5">
			<sentence id="5.1">##Just in case I'm an idiot and referencing a different base image</sentence>
			<sentence id="5.2">$ sudo docker build .</sentence>
			<sentence id="5.3">Sending build context to Docker daemon 20.48 kB</sentence>
			<sentence id="5.4">Sending build context to Docker daemon</sentence>
			<sentence id="5.5">Step 0 : FROM bunchballdev/fedora</sentence>
			<sentence id="5.6">---&gt; 33a9229518a7</sentence>
			<sentence id="5.7">Step 1 : RUN echo "got here"</sentence>
			<sentence id="5.8">---&gt; Running in f9175b949870</sentence>
			<sentence id="5.9">got here</sentence>
			<sentence id="5.10">---&gt; 141398bf5586</sentence>
			<sentence id="5.11">Removing intermediate container f9175b949870</sentence>
			<sentence id="5.12">Successfully built 141398bf5586</sentence>
		</paragraph>
		<paragraph id="6">
			<sentence id="6.1">soooooo, docker build is somehow using a different authfile than docker pull, but I don't see how that could be given the following:
https://github.com/docker/docker/blob/master/api/client/build.go#L281</sentence>
		</paragraph>
		<paragraph id="7">
			<sentence id="7.1">Here's my specs:
$ sudo docker -D info
Containers: 0
Images: 242
Storage Driver: btrfs
 Build Version: Btrfs v4.0
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.3-200.</sentence>
			<sentence id="7.2">fc21.x86_64
Operating System: Fedora 21 (Twenty One)
CPUs: 4
Total Memory: 14.69 GiB
Name: &lt;hostname&gt;
ID: C3GX:NQYI:PVQJ:3YK3:K4WT:EMMF:PKEG:XNDG:QO6S:FKCS:62LI:5WQT
Username: &lt;username&gt;
Registry: https://index.docker.io/v1/</sentence>
		</paragraph>
		<paragraph id="8">
			<sentence id="8.1">$ sudo docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609-dirty
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609-dirty
OS/Arch (server): linux/amd64</sentence>
		</paragraph>
	</description>
</bug>
